import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { AppButton, Card, Content, PageHeader, Screen, Skeleton } from '@/components/ui';
import { usePoints } from '@/context/PointsContext';
import { COMMUNITY_REWARD_TIERS, getRewardProgress } from '@/features/community';
import { useAppTheme } from '@/theme';
import { useAppLocale } from '@/context/AppLocaleContext';

export default function CommunityRewardsScreen() {
  const { theme } = useAppTheme();
  const { locale, t } = useAppLocale();
  const router = useRouter();
  const { pointBalance, isBalanceLoading, refreshBalance } = usePoints();
  useFocusEffect(useCallback(() => { void refreshBalance(); }, [refreshBalance]));
  const progress = getRewardProgress(pointBalance.total);

  return <Screen><ScrollView showsVerticalScrollIndicator={false}><Content>
    <PageHeader eyebrow={t('Virtual rewards', 'Виртуални награди')} title={t('Green points and achievements', 'Зелени точки и постижения')} description={t('Earn points through verified app activity, community participation, completed challenges, and approved contributions.', 'Печелете точки чрез проверена активност, участие в общността, завършени предизвикателства и одобрени приноси.')} action={<AppButton label={t('Back', 'Назад')} icon="arrow-back" variant="ghost" onPress={() => router.back()} />} />
    {isBalanceLoading ? <Skeleton height={180} /> : <Card elevated style={{ gap: theme.spacing.md, marginBottom: theme.spacing.xl, backgroundColor: theme.colors.primarySoft }}><Text style={[theme.typography.label, { color: theme.colors.primary, textTransform: 'uppercase' }]}>{t('Current balance', 'Текущ баланс')}</Text><Text style={[theme.typography.display, { color: theme.colors.text }]}>{pointBalance.total.toLocaleString()} {t('points', 'точки')}</Text>{progress.next ? <><Text style={[theme.typography.body, { color: theme.colors.textMuted }]}>{progress.pointsToNext.toLocaleString()} {t('points until', 'точки до')} {locale === 'bg' ? ({ seedling: 'Фиданка', 'community-builder': 'Създател на общност', 'planet-ally': 'Съюзник на планетата' }[progress.next.id] || progress.next.name) : progress.next.name}</Text><View style={{ height: 10, backgroundColor: theme.colors.surfaceStrong, borderRadius: 5, overflow: 'hidden' }}><View style={{ height: '100%', width: `${Math.min(100, Math.round((pointBalance.total / progress.next.pointsRequired) * 100))}%`, backgroundColor: theme.colors.primary }} /></View></> : <Text style={[theme.typography.h3, { color: theme.colors.success }]}>{t('All community tiers unlocked', 'Всички нива на общността са отключени')}</Text>}</Card>}

    <Text accessibilityRole="header" style={[theme.typography.h2, { color: theme.colors.text, marginBottom: theme.spacing.md }]}>{t('Community reward tiers', 'Нива на наградите')}</Text>
    <View style={{ gap: theme.spacing.md }}>{COMMUNITY_REWARD_TIERS.map((tier) => { const unlocked = pointBalance.total >= tier.pointsRequired; const bg = { seedling: ['Фиданка', 'Дигитален етап за начало на вашите зелени навици.'], 'community-builder': ['Създател на общност', 'Отличава постоянните действия и споделянето на знания.'], 'planet-ally': ['Съюзник на планетата', 'Отбелязва дългосрочното въздействие върху общността.'] }[tier.id]; return <Card key={tier.id} style={{ flexDirection: 'row', alignItems: 'center', gap: theme.spacing.md, opacity: unlocked ? 1 : 0.72 }}><View style={{ width: 52, height: 52, borderRadius: 18, backgroundColor: unlocked ? theme.colors.accentSoft : theme.colors.surfaceMuted, alignItems: 'center', justifyContent: 'center' }}><Ionicons name={unlocked ? tier.icon : 'lock-closed-outline'} size={25} color={unlocked ? theme.colors.primary : theme.colors.textMuted} /></View><View style={{ flex: 1 }}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>{locale === 'bg' && bg ? bg[0] : tier.name}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 3 }]}>{locale === 'bg' && bg ? bg[1] : tier.description}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={[theme.typography.label, { color: unlocked ? theme.colors.success : theme.colors.textMuted }]}>{unlocked ? t('UNLOCKED', 'ОТКЛЮЧЕНО') : `${tier.pointsRequired} ${t('PTS', 'Т.')}`}</Text></View></Card>; })}</View>

    <Card style={{ marginTop: theme.spacing.xl, gap: theme.spacing.md }}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>{t('Achievement paths', 'Пътеки на постиженията')}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 9 }}>{[['Plastic-Free Hero', 'Герой без пластмаса'], ['Eco Commuter', 'Еко пътешественик'], ['Zero-Waste Champion', 'Шампион без отпадъци'], ['Power of We', 'Силата на заедността']].map(([en, bg]) => <View key={en} style={{ borderRadius: theme.radii.pill, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: theme.colors.surfaceMuted }}><Text style={[theme.typography.label, { color: theme.colors.text }]}>{t(en, bg)}</Text></View>)}</View><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>{t('Badges are awarded from tracked habits, streaks, goals, challenges, and community events.', 'Значките се присъждат за проследени навици, серии, цели, предизвикателства и събития на общността.')}</Text><AppButton label={t('View earned badges', 'Виж спечелените значки')} icon="ribbon-outline" onPress={() => router.push('/profile/badges' as any)} /></Card>
  </Content></ScrollView></Screen>;
}
