import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { AppButton, Card, Content, PageHeader, Screen, StatePanel } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { KNOWLEDGE_TOPICS, LEARNING_PATHS, knowledgeService, localizedTopic, useKnowledgeLocale, type CertificateVerification, type KnowledgeLearningProfile } from '@/features/knowledge';
import { useAppTheme } from '@/theme';

export default function MyLearningScreen() {
  const { theme } = useAppTheme();
  const { user } = useAuth();
  const { locale, t } = useKnowledgeLocale();
  const router = useRouter();
  const [profile, setProfile] = useState<KnowledgeLearningProfile | null>(null);
  const [paths, setPaths] = useState<{ slug: string; title: string; percent: number }[]>([]);
  const [certificates, setCertificates] = useState<CertificateVerification[]>([]);
  useFocusEffect(useCallback(() => { if (user) void Promise.all([
    knowledgeService.getLearningProfile(user.id),
    knowledgeService.getCertificates(user.id),
    Promise.all(LEARNING_PATHS.filter((path) => path.locale === locale).map((path) => knowledgeService.getLearningPathProgress(user.id, path.slug, locale))),
  ]).then(([nextProfile, nextCertificates, pathProgress]) => {
    setProfile(nextProfile); setCertificates(nextCertificates);
    setPaths(pathProgress.filter((entry) => entry && entry.percent > 0).map((entry) => ({ slug: entry!.path.slug, title: entry!.path.title, percent: entry!.percent })));
  }); }, [user, locale]));

  if (!user) return <Screen><Content><PageHeader eyebrow={t('Personal learning', 'Лично обучение')} title={t('My Learning', 'Моето обучение')} description={t('The library stays open to everyone. Sign in to save progress, rewards and missions.', 'Библиотеката остава отворена за всички. Влезте, за да пазите прогрес, награди и мисии.')} /><StatePanel icon="lock-closed-outline" title={t('Sign in to track your journey', 'Влезте, за да следите пътя си')} message={t('Your Green Points, Knowledge badges, challenges and quests are tied to your account.', 'Green Points, Knowledge badges, предизвикателствата и мисиите са свързани с профила ви.')} action={<AppButton label={t('Sign in', 'Вход')} onPress={() => router.push('/auth/signin')} />} /></Content></Screen>;
  if (!profile) return <Screen><Content><PageHeader eyebrow={t('Personal learning', 'Лично обучение')} title={t('My Learning', 'Моето обучение')} /><StatePanel icon="hourglass-outline" title={t('Building your learning profile', 'Подготвяме учебния ви профил')} message={t('Progress and rewards are being synchronized.', 'Прогресът и наградите се синхронизират.')} /></Content></Screen>;

  const next = profile.nextLevel;
  const levelRange = next ? next.minimumXp - profile.level.minimumXp : Math.max(profile.learningXp, 1);
  const levelProgress = next ? Math.round(((profile.learningXp - profile.level.minimumXp) / levelRange) * 100) : 100;
  return <Screen><ScrollView showsVerticalScrollIndicator={false}><Content wide>
    <PageHeader eyebrow={t('Personal learning', 'Лично обучение')} title={t('My Learning', 'Моето обучение')} description={t('One place for your learning level, topic progress, missions, badges and certificates.', 'Едно място за вашето ниво, напредък по теми, мисии, значки и сертификати.')} />
    <Card elevated style={{ backgroundColor: theme.colors.primary, marginBottom: 20 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 16 }}><View style={{ width: 58, height: 58, borderRadius: 20, backgroundColor: '#FFFFFF22', alignItems: 'center', justifyContent: 'center' }}><Ionicons name="school-outline" size={29} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={[theme.typography.label, { color: theme.colors.accent }]}>{t('LEARNING LEVEL', 'УЧЕБНО НИВО')}</Text><Text style={[theme.typography.h1, { color: '#FFFFFF', marginTop: 3 }]}>{profile.level.name[locale]}</Text><Text style={[theme.typography.bodySmall, { color: '#D8EAE0', marginTop: 4 }]}>{profile.learningXp} {t('learning XP', 'учебни XP')} • {profile.totalGreenPoints} {t('Green Points', 'зелени точки')}</Text></View></View><View style={{ height: 8, borderRadius: 4, overflow: 'hidden', backgroundColor: '#FFFFFF2B', marginTop: 20 }}><View style={{ width: `${levelProgress}%`, height: '100%', backgroundColor: theme.colors.accent }} /></View><Text style={[theme.typography.bodySmall, { color: '#D8EAE0', marginTop: 8 }]}>{next ? t(`${next.minimumXp - profile.learningXp} XP to ${next.name.en}`, `${next.minimumXp - profile.learningXp} XP до ${next.name.bg}`) : t('Highest learning level reached', 'Достигнато е най-високото ниво')}</Text></Card>

    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 26 }}><Metric value={profile.completedItems} label={t('Completed', 'Завършени')} icon="checkmark-circle-outline" /><Metric value={profile.completedQuizzes} label={t('Quizzes passed', 'Издържани тестове')} icon="help-circle-outline" /><Metric value={profile.completedInteractives} label={t('Interactive tools', 'Интерактивни инструменти')} icon="flask-outline" /></View>

    {(profile.activeChallenge || profile.activeQuest) ? <><Text accessibilityRole="header" style={[theme.typography.h2, { color: theme.colors.text, marginBottom: 12 }]}>{t('Active missions', 'Активни мисии')}</Text><View style={{ gap: 10, marginBottom: 28 }}>{profile.activeChallenge ? <Card><Text style={[theme.typography.label, { color: theme.colors.primary }]}>{t('LEARNING CHALLENGE', 'УЧЕБНО ПРЕДИЗВИКАТЕЛСТВО')}</Text><Text style={[theme.typography.h3, { color: theme.colors.text, marginTop: 5 }]}>{knowledgeService.getChallenge(profile.activeChallenge.challengeId)?.title[locale]}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 5 }]}>{profile.activeChallenge.completedStepIds.length} {t('steps complete', 'завършени стъпки')}</Text><AppButton label={t('Continue', 'Продължи')} onPress={() => router.push(`/knowledge/challenge/${profile.activeChallenge!.challengeId}` as any)} style={{ marginTop: 12, alignSelf: 'flex-start' }} /></Card> : null}{profile.activeQuest ? <Card><Text style={[theme.typography.label, { color: theme.colors.primary }]}>{t('KNOWLEDGE QUEST', 'МИСИЯ ЗА ЗНАНИЯ')}</Text><Text style={[theme.typography.h3, { color: theme.colors.text, marginTop: 5 }]}>{knowledgeService.getQuest(profile.activeQuest.questId)?.title[locale]}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 5 }]}>{profile.activeQuest.completedNodeIds.length} {t('nodes explored', 'разгледани точки')}</Text><AppButton label={t('Continue', 'Продължи')} onPress={() => router.push(`/knowledge/quest/${profile.activeQuest!.questId}` as any)} style={{ marginTop: 12, alignSelf: 'flex-start' }} /></Card> : null}</View></> : null}

    <Text accessibilityRole="header" style={[theme.typography.h2, { color: theme.colors.text, marginBottom: 12 }]}>{t('Paths & certificates', 'Пътеки и сертификати')}</Text>
    <View style={{ gap: 10, marginBottom: 28 }}>{paths.map((path) => <Card key={path.slug}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>{path.title}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 5 }]}>{path.percent}% {t('complete', 'завършено')}</Text><AppButton label={t('Continue path', 'Продължи пътеката')} variant="secondary" onPress={() => router.push(`/knowledge/path/${path.slug}` as any)} style={{ marginTop: 10, alignSelf: 'flex-start' }} /></Card>)}{certificates.map((certificate) => <Card key={certificate.code}><View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><Ionicons name="ribbon-outline" size={25} color={theme.colors.primary} /><View style={{ flex: 1 }}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>{certificate.pathTitle}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 3 }]}>{t('Certificate of completion', 'Сертификат за завършване')} • {certificate.status}</Text></View><AppButton label={t('View', 'Виж')} variant="ghost" onPress={() => router.push(`/knowledge/certificate/${certificate.code}` as any)} /></View></Card>)}{paths.length === 0 && certificates.length === 0 ? <Card><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>{t('Start a learning path to see progress and certificates here.', 'Започнете учебна пътека, за да виждате напредъка и сертификатите тук.')}</Text></Card> : null}</View>

    <Text accessibilityRole="header" style={[theme.typography.h2, { color: theme.colors.text, marginBottom: 12 }]}>{t('Progress by topic', 'Напредък по теми')}</Text>
    <Card style={{ padding: 0, overflow: 'hidden', marginBottom: 28 }}>{KNOWLEDGE_TOPICS.map((topic, index) => { const percent = profile.topicProgress[topic.slug] || 0; const copy = localizedTopic(topic, locale); return <View key={topic.slug} style={{ padding: 16, borderBottomWidth: index === KNOWLEDGE_TOPICS.length - 1 ? 0 : 1, borderBottomColor: theme.colors.border }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><Ionicons name={topic.icon as any} size={19} color={topic.visual.palette.primary} /><Text style={[theme.typography.label, { color: theme.colors.text, flex: 1 }]}>{copy.name}</Text><Text style={[theme.typography.label, { color: theme.colors.textMuted }]}>{percent}%</Text></View><View style={{ height: 5, borderRadius: 3, backgroundColor: theme.colors.surfaceStrong, overflow: 'hidden', marginTop: 9 }}><View style={{ width: `${percent}%`, height: '100%', backgroundColor: topic.visual.palette.primary }} /></View></View>; })}</Card>

    <Text accessibilityRole="header" style={[theme.typography.h2, { color: theme.colors.text, marginBottom: 12 }]}>{t('Knowledge badges', 'Knowledge значки')}</Text>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{profile.badges.map((badge) => <Card key={badge.code} style={{ width: '48%', minWidth: 160, opacity: badge.earned ? 1 : 0.58 }}><Ionicons name={badge.earned ? 'ribbon' : 'lock-closed-outline'} size={25} color={badge.earned ? theme.colors.primary : theme.colors.textMuted} /><Text style={[theme.typography.h3, { color: theme.colors.text, marginTop: 9 }]}>{badge.name[locale]}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted, marginTop: 5 }]}>{badge.description[locale]}</Text></Card>)}</View>
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 24 }}><AppButton label={t('Explore missions', 'Разгледай мисиите')} icon="compass-outline" onPress={() => router.replace({ pathname: '/knowledge' as any, params: { view: 'missions' } })} /><AppButton label={t('Edit interests', 'Редактирай интересите')} variant="secondary" icon="options-outline" onPress={() => router.push('/knowledge/preferences' as any)} /></View>
  </Content></ScrollView></Screen>;
}

function Metric({ value, label, icon }: { value: number; label: string; icon: keyof typeof Ionicons.glyphMap }) {
  const { theme } = useAppTheme();
  return <Card style={{ minWidth: 150, flex: 1 }}><Ionicons name={icon} size={21} color={theme.colors.primary} /><Text style={[theme.typography.metric, { color: theme.colors.text, marginTop: 8 }]}>{value}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>{label}</Text></Card>;
}
