import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { AppButton, AppInput, Card, Content, PageHeader, Screen, Skeleton, StatePanel } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { useNotification } from '@/context/NotificationContext';
import { MapBudgetStatus, sustainabilityMapAdminService } from '@/features/sustainability-map';
import { useAppTheme } from '@/theme';

function PercentBar({ value, color }: { value: number; color: string }) { const { theme } = useAppTheme(); return <View style={{ height: 9, borderRadius: 5, backgroundColor: theme.colors.surfaceMuted, overflow: 'hidden' }}><View style={{ width: `${Math.min(100,Math.max(0,value))}%`, height: '100%', backgroundColor: color }} /></View>; }

export default function MapAdminScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const { user } = useAuth(); const { addNotification } = useNotification();
  const roles = (user?.app_metadata?.knowledge_roles || []) as string[]; const reviewer = roles.some((role) => ['reviewer','publisher'].includes(role)); const publisher = roles.includes('publisher');
  const [budget,setBudget] = useState<MapBudgetStatus | null>(null); const [queue,setQueue] = useState<{submissions:any[];reviews:any[];media:any[]}>({submissions:[],reviews:[],media:[]}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState('');
  const [webLimit,setWebLimit]=useState('45000'); const [mobileLimit,setMobileLimit]=useState('22500'); const [periodStart,setPeriodStart]=useState(''); const [periodEnd,setPeriodEnd]=useState(''); const [message,setMessage]=useState('');
  const load = useCallback(async () => { if (!reviewer) return; setLoading(true); try { const [nextBudget,nextQueue]=await Promise.all([sustainabilityMapAdminService.getBudgetStatus(),sustainabilityMapAdminService.listModerationQueue()]); setBudget(nextBudget); setQueue(nextQueue); setWebLimit(String(nextBudget.webLimit)); setMobileLimit(String(nextBudget.mobileLimit)); setPeriodStart(nextBudget.periodStart); setPeriodEnd(nextBudget.periodEnd); setMessage(nextBudget.message); } catch(error){ addNotification({type:'toast',severity:'error',message:error instanceof Error?error.message:'Unable to load map administration.'}); } finally { setLoading(false); } },[addNotification,reviewer]);
  useFocusEffect(useCallback(() => { void load(); },[load]));
  if (!reviewer) return <Screen><Content><StatePanel icon="lock-closed-outline" title="Reviewer access required" message="Map budgets, imports and moderation are protected by reviewer and publisher roles." action={<AppButton label="Back" onPress={() => router.back()} />} /></Content></Screen>;
  const moderate = async (kind:'submission'|'review'|'media',id:string,status:'approved'|'rejected') => { setBusy(id); try { await sustainabilityMapAdminService.moderate(kind,id,status); await load(); addNotification({type:'toast',severity:'success',message:status==='approved'?'Approved and rewarded.':'Rejected.'}); } catch(error){addNotification({type:'toast',severity:'error',message:error instanceof Error?error.message:'Moderation failed.'});} finally{setBusy('');} };
  const saveBudget = async (enabled:boolean) => { setBusy('budget'); try { await sustainabilityMapAdminService.setBudget({enabled,webLimit:Number(webLimit),mobileLimit:Number(mobileLimit),periodStart,periodEnd,message}); await load(); addNotification({type:'toast',severity:'success',message:enabled?'Interactive map enabled with the protected budget.':'Emergency switch disabled the interactive map.'}); } catch(error){addNotification({type:'toast',severity:'error',message:error instanceof Error?error.message:'Budget update failed.'});} finally{setBusy('');} };
  const importEV = async () => { setBusy('import'); try { const result=await sustainabilityMapAdminService.importBundledEVLocations(); await load(); addNotification({type:'toast',severity:'success',message:`Imported ${result.locations} places and ${result.connectors} connectors.`}); } catch(error){addNotification({type:'toast',severity:'error',message:error instanceof Error?error.message:'Import failed.'});} finally{setBusy('');} };
  const renderQueue = (kind:'submission'|'review'|'media',items:any[]) => <View style={{gap:10}}>{items.length===0?<Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>Queue clear.</Text>:items.map((item)=><Card key={item.id} style={{gap:8}}><Text style={[theme.typography.label,{color:theme.colors.primary,textTransform:'uppercase'}]}>{kind}</Text><Text style={[theme.typography.h3,{color:theme.colors.text}]}>{item.proposed_data?.name||item.sustainability_locations?.name||item.storage_path||'Map contribution'}</Text>{item.body?<Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>{item.body}</Text>:null}{item.proposed_data?<Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>{JSON.stringify(item.proposed_data)}</Text>:null}<View style={{flexDirection:'row',gap:8}}><AppButton label="Approve" icon="checkmark" loading={busy===item.id} onPress={()=>void moderate(kind,item.id,'approved')} style={{flex:1}}/><AppButton label="Reject" variant="danger" disabled={Boolean(busy)} onPress={()=>void moderate(kind,item.id,'rejected')} style={{flex:1}}/></View></Card>)}</View>;
  return <Screen><ScrollView><Content wide><PageHeader eyebrow="Protected operations" title="Sustainability Map administration" description="Control Mapbox exposure, import the licensed connector catalogue and moderate every public claim." action={<AppButton label="Back to map" icon="arrow-back" variant="ghost" onPress={()=>router.replace('/map')}/>} />{loading?<><Skeleton height={240}/><Skeleton height={260} style={{marginTop:12}}/></>:<View style={{gap:theme.spacing.xl}}>
    {budget?<Card elevated style={{gap:theme.spacing.md}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={[theme.typography.h2,{color:theme.colors.text}]}>Mapbox budget guard</Text><Text style={[theme.typography.bodySmall,{color:budget.enabled?theme.colors.success:theme.colors.danger}]}>{budget.enabled?'Interactive map enabled':'Emergency switch OFF'}</Text></View><AppButton label={budget.enabled?'Pause globe':'Enable globe'} variant={budget.enabled?'danger':'primary'} disabled={!publisher} loading={busy==='budget'} onPress={()=>void saveBudget(!budget.enabled)}/></View><View style={{gap:6}}><Text style={[theme.typography.label,{color:theme.colors.text}]}>Web · {budget.webUsed.toLocaleString()} / {budget.webLimit.toLocaleString()} ({Math.round(budget.webUsed/budget.webLimit*100)}%)</Text><PercentBar value={budget.webUsed/budget.webLimit*100} color={budget.webUsed/budget.webLimit>=.95?theme.colors.danger:budget.webUsed/budget.webLimit>=.7?theme.colors.warning:theme.colors.success}/></View><View style={{gap:6}}><Text style={[theme.typography.label,{color:theme.colors.text}]}>Mobile · {budget.mobileUsed.toLocaleString()} / {budget.mobileLimit.toLocaleString()} ({Math.round(budget.mobileUsed/budget.mobileLimit*100)}%)</Text><PercentBar value={budget.mobileUsed/budget.mobileLimit*100} color={budget.mobileUsed/budget.mobileLimit>=.95?theme.colors.danger:budget.mobileUsed/budget.mobileLimit>=.7?theme.colors.warning:theme.colors.success}/></View>{publisher?<View style={{gap:10}}><View style={{flexDirection:'row',gap:10}}><AppInput label="Web limit" value={webLimit} onChangeText={setWebLimit} keyboardType="number-pad" style={{flex:1}}/><AppInput label="Mobile limit" value={mobileLimit} onChangeText={setMobileLimit} keyboardType="number-pad" style={{flex:1}}/></View><View style={{flexDirection:'row',gap:10}}><AppInput label="Period start" value={periodStart} onChangeText={setPeriodStart} placeholder="YYYY-MM-DD" style={{flex:1}}/><AppInput label="Period end" value={periodEnd} onChangeText={setPeriodEnd} placeholder="YYYY-MM-DD" style={{flex:1}}/></View><AppInput label="Unavailable message" value={message} onChangeText={setMessage}/><AppButton label="Save limits" variant="secondary" loading={busy==='budget'} onPress={()=>void saveBudget(budget.enabled)}/></View>:<Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>Publisher role is required to change the budget.</Text>}</Card>:null}
    <Card style={{gap:theme.spacing.md}}><Text style={[theme.typography.h2,{color:theme.colors.text}]}>Licensed EV bootstrap</Text><Text style={[theme.typography.body,{color:theme.colors.textMuted}]}>Idempotently imports 57 physical Open Charge Map places and their 89 connector records. Existing records are updated, not duplicated.</Text><AppButton label="Import bundled EV catalogue" icon="cloud-upload-outline" loading={busy==='import'} onPress={()=>void importEV()}/></Card>
    <View><Text style={[theme.typography.h2,{color:theme.colors.text,marginBottom:12}]}>Location submissions ({queue.submissions.length})</Text>{renderQueue('submission',queue.submissions)}</View><View><Text style={[theme.typography.h2,{color:theme.colors.text,marginBottom:12}]}>Reviews ({queue.reviews.length})</Text>{renderQueue('review',queue.reviews)}</View><View><Text style={[theme.typography.h2,{color:theme.colors.text,marginBottom:12}]}>Photos ({queue.media.length})</Text>{renderQueue('media',queue.media)}</View>
  </View>}</Content></ScrollView></Screen>;
}
