import React, { useEffect, useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppButton, Card, Content, PageHeader, Screen, Skeleton, StatePanel } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { sustainabilityMapService } from '@/features/sustainability-map';
import { useAppTheme } from '@/theme';
import { PersonalMapImpact } from '@/types/map';
import { getCategoryConfig } from '@/utils/categoryUtils';

export default function MapImpactScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const { user } = useAuth();
  const [impact, setImpact] = useState<PersonalMapImpact | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!user) return; void sustainabilityMapService.getMyImpact().then(setImpact).catch((value) => setError(value instanceof Error ? value.message : 'Unable to load impact.')); }, [user]);
  if (!user) return <Screen><Content><StatePanel icon="lock-closed-outline" title="Sign in to view impact" message="Your visit history and estimates are private to your account." /></Content></Screen>;
  return <Screen><ScrollView><Content><PageHeader eyebrow="Private impact" title="Your sustainability map journey" description="Visits are factual check-ins. Resource estimates appear only when a published methodology and measurable input are available." action={<AppButton label="Back to map" icon="arrow-back" variant="ghost" onPress={() => router.back()} />} />{error ? <StatePanel icon="alert-circle-outline" title="Impact unavailable" message={error} /> : !impact ? <><Skeleton height={140} /><Skeleton height={180} style={{ marginTop: 12 }} /></> : <View style={{ gap: theme.spacing.md }}><View style={{ flexDirection: 'row', gap: theme.spacing.md, flexWrap: 'wrap' }}><Card elevated style={{ flex: 1, minWidth: 220 }}><Text style={[theme.typography.h1, { color: theme.colors.primary }]}>{impact.visitCount}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>recorded visits</Text></Card><Card elevated style={{ flex: 1, minWidth: 220 }}><Text style={[theme.typography.h1, { color: theme.colors.primary }]}>{impact.uniqueLocations}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>unique verified places</Text></Card></View><Card style={{ gap: 10 }}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>Visits by category</Text>{Object.entries(impact.byCategory).length ? Object.entries(impact.byCategory).map(([id,count]) => <View key={id} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: theme.colors.border }}><Text style={[theme.typography.body, { color: theme.colors.text }]}>{getCategoryConfig(id as any).label}</Text><Text style={[theme.typography.label, { color: theme.colors.primary }]}>{count}</Text></View>) : <Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>Check in at your first verified place to begin.</Text>}</Card><Card style={{ gap: 10 }}><Text style={[theme.typography.h3, { color: theme.colors.text }]}>Documented estimates</Text>{impact.estimates.length ? impact.estimates.map((estimate) => <View key={`${estimate.metric}:${estimate.methodologyVersion}`}><Text style={[theme.typography.label, { color: theme.colors.text }]}>{estimate.value.toFixed(2)} {estimate.unit}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>Estimate · methodology {estimate.methodologyVersion}</Text></View>) : <Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>No resource estimate is shown from a visit alone. Green Compass will never translate an EV-station check-in directly into avoided CO₂.</Text>}</Card></View>}</Content></ScrollView></Screen>;
}
