import React, { useEffect, useState } from 'react';
import { Linking, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AppButton, Card, Content, PageHeader, Screen, Skeleton, StatePanel } from '@/components/ui';
import { sustainabilityMapService } from '@/features/sustainability-map';
import { useAppTheme } from '@/theme';
import { EcoRoute } from '@/types/map';
import { formatAddress, getPlatformSpecificNavigationUrl } from '@/utils/mapUtils';

export default function EcoRoutesScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const [routes,setRoutes] = useState<EcoRoute[] | null>(null); const [error,setError] = useState('');
  useEffect(() => { void sustainabilityMapService.listRoutes().then(setRoutes).catch((value) => setError(value instanceof Error ? value.message : 'Unable to load routes.')); }, []);
  return <Screen><ScrollView><Content wide><PageHeader eyebrow="Curated discovery" title="Eco‑Tour routes" description="Editor-reviewed routes connect verified places around one practical sustainability theme. Navigation opens one stop at a time in your preferred maps app." action={<AppButton label="Back to map" icon="arrow-back" variant="ghost" onPress={() => router.back()} />} />{error ? <StatePanel icon="alert-circle-outline" title="Routes unavailable" message={error} /> : !routes ? <Skeleton height={220} /> : routes.length === 0 ? <StatePanel icon="trail-sign-outline" title="Routes are being curated" message="The route layer stays hidden until editors publish a complete sequence of verified stops." /> : <View style={{ gap: theme.spacing.lg }}>{routes.map((route) => <Card key={route.id} elevated style={{ gap: theme.spacing.md }}><View><Text style={[theme.typography.h2, { color: theme.colors.text }]}>{route.title}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>{route.durationMinutes} min · {route.stops.length} stops</Text></View><Text style={[theme.typography.body, { color: theme.colors.textMuted }]}>{route.description}</Text>{route.stops.map((stop) => <View key={stop.order} style={{ flexDirection: 'row', gap: 12, paddingTop: 10, borderTopWidth: 1, borderTopColor: theme.colors.border }}><View style={{ width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.colors.primary }}><Text style={[theme.typography.label, { color: theme.colors.textInverse }]}>{stop.order}</Text></View><View style={{ flex: 1 }}><Text style={[theme.typography.label, { color: theme.colors.text }]}>{stop.location.name}</Text><Text style={[theme.typography.bodySmall, { color: theme.colors.textMuted }]}>{stop.note || formatAddress(stop.location)}</Text></View><AppButton label="Navigate" icon="navigate-outline" variant="ghost" onPress={() => void Linking.openURL(getPlatformSpecificNavigationUrl(stop.location.lat,stop.location.lng,stop.location.name,formatAddress(stop.location)))} /></View>)}</Card>)}</View>}</Content></ScrollView></Screen>;
}
