import React, { useCallback, useEffect, useState } from 'react';
import { Image, ScrollView, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AppButton, AppInput, Card, Content, Screen, Skeleton, StatePanel } from '@/components/ui';
import { MarketplaceHeader } from '@/features/marketplace/components';
import { formatMarketplacePrice, marketplaceService, type MarketplaceProductDetail } from '@/features/marketplace';
import { useAuth } from '@/context/AuthContext'; import { useAppLocale } from '@/context/AppLocaleContext'; import { useAppTheme } from '@/theme';

export default function MarketplaceProductScreen(){
  const {slug}=useLocalSearchParams<{slug:string}>(); const router=useRouter(); const {user}=useAuth(); const {locale,t}=useAppLocale(); const {theme}=useAppTheme();
  const [product,setProduct]=useState<MarketplaceProductDetail|null>(null); const [error,setError]=useState<string|null>(null); const [adding,setAdding]=useState(false);
  const [wishlist,setWishlist]=useState(false); const [reviews,setReviews]=useState<{id:string;rating:number;body:string;verifiedPurchase:boolean;authorName:string;createdAt:string}[]>([]); const [reviewBody,setReviewBody]=useState(''); const [reviewRating,setReviewRating]=useState('5'); const [reviewSent,setReviewSent]=useState(false);
  const load=useCallback(async()=>{setError(null);try{const next=await marketplaceService.getProduct(slug);setProduct(next);if(next){setReviews(await marketplaceService.listApprovedReviews(next.id));if(user)setWishlist((await marketplaceService.listWishlistIds()).includes(next.id));}}catch(e){setError(e instanceof Error?e.message:t('Product unavailable.','Продуктът не е достъпен.'));}},[slug,t,user]); useEffect(()=>{void load();},[load]);
  const add=async(replace=false)=>{if(!product)return;if(!user){router.push({pathname:'/auth/signin' as any,params:{redirect:`/marketplace/product/${slug}`}});return;}setAdding(true);try{await marketplaceService.setCartItem(product.id,1,product.stockQuantity,replace);router.push('/marketplace/cart' as any);}catch(e){const message=e instanceof Error?e.message:'';if(message.includes('CART_BUSINESS_MISMATCH')){setError(t('Your cart contains another business. Clear it from the cart before adding this product.','Количката съдържа друг бизнес. Изчистете я, преди да добавите продукта.'));}else setError(message);}finally{setAdding(false);}};
  return <Screen><ScrollView><Content wide><MarketplaceHeader showBack />{!product&&!error?<Skeleton height={420}/>:null}{error?<StatePanel title={t('Product unavailable','Продуктът не е достъпен')} message={error} action={<AppButton label={t('Try again','Опитайте отново')} onPress={()=>void load()}/>} />:null}{product?<>
    <View style={{flexDirection:'row',flexWrap:'wrap',gap:26}}><View style={{flex:1,minWidth:280}}>{product.imageUrl?<Image source={{uri:product.imageUrl}} accessibilityLabel={product.imageAlt[locale]} style={{width:'100%',height:420,borderRadius:theme.radii.lg,backgroundColor:theme.colors.surfaceMuted}} resizeMode="cover"/>:<View style={{height:420,borderRadius:theme.radii.lg,backgroundColor:theme.colors.primarySoft}}/>}</View><View style={{flex:1,minWidth:280}}>
      <Text style={[theme.typography.label,{color:theme.colors.primary}]}>{product.business.verified?t('VERIFIED BUSINESS','ПРОВЕРЕН БИЗНЕС'):''}</Text><Text style={[theme.typography.h1,{color:theme.colors.text,marginTop:6}]}>{product.name[locale]}</Text><Text style={[theme.typography.body,{color:theme.colors.textMuted,marginTop:8}]}>{product.summary[locale]}</Text>
      <Text style={[theme.typography.metric,{color:theme.colors.text,marginTop:18}]}>{formatMarketplacePrice(product.priceCents,locale)}</Text><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted,marginTop:5}]}>{t('VAT included. Shipping calculated from the partner tariff.','Цената включва ДДС. Доставката се изчислява по тарифата на партньора.')}</Text>
      <Card style={{marginTop:18}}><Text style={[theme.typography.h3,{color:theme.colors.text}]}>{t('Sustainability rating','Оценка за устойчивост')}: {product.sustainabilityRating.toFixed(1)}/5</Text><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted,marginTop:4}]}>{t('Evidence-backed editorial score, separate from customer reviews.','Редакторска оценка с доказателства, отделна от потребителските отзиви.')}</Text></Card>
      <AppButton label={product.stockQuantity?t('Add to cart','Добави в количката'):t('Out of stock','Изчерпан')} icon="bag-add-outline" loading={adding} disabled={!product.stockQuantity} onPress={()=>void add()} style={{marginTop:18}} />
      <AppButton label={wishlist?t('Saved to wishlist','Запазено в любими'):t('Save to wishlist','Запази в любими')} icon={wishlist?'heart':'heart-outline'} variant="secondary" onPress={async()=>{if(!user){router.push({pathname:'/auth/signin' as any,params:{redirect:`/marketplace/product/${slug}`}});return;}const next=!wishlist;setWishlist(next);try{await marketplaceService.toggleWishlist(user.id,product.id,next);}catch(e){setWishlist(!next);setError(e instanceof Error?e.message:String(e));}}} style={{marginTop:8}} />
      <AppButton label={product.business.name} icon="storefront-outline" variant="ghost" onPress={()=>router.push(`/marketplace/business/${product.business.slug}` as any)} style={{marginTop:8}} />
    </View></View>
    <Card style={{marginTop:26}}><Text style={[theme.typography.h2,{color:theme.colors.text}]}>{t('Product details','Детайли за продукта')}</Text><Text style={[theme.typography.body,{color:theme.colors.textMuted,marginTop:8}]}>{product.description[locale]}</Text>{product.materials[locale]?<><Text style={[theme.typography.h3,{color:theme.colors.text,marginTop:18}]}>{t('Materials','Материали')}</Text><Text style={[theme.typography.body,{color:theme.colors.textMuted,marginTop:5}]}>{product.materials[locale]}</Text></>:null}</Card>
    {product.certifications.length?<Card style={{marginTop:14}}><Text style={[theme.typography.h2,{color:theme.colors.text}]}>{t('Verified certifications','Проверени сертификати')}</Text>{product.certifications.map(c=><View key={c.id} style={{marginTop:12}}><Text style={[theme.typography.h3,{color:theme.colors.text}]}>{c.name}</Text><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>{c.issuer}</Text></View>)}</Card>:null}
    {product.impactClaims.length?<Card style={{marginTop:14,backgroundColor:theme.colors.accentSoft}}><Text style={[theme.typography.h2,{color:theme.colors.text}]}>{t('Potential impact','Потенциално въздействие')}</Text><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted,marginTop:4}]}>{t('These estimates become observed impact only after you confirm product use.','Тези оценки стават наблюдавано въздействие само след потвърдена употреба.')}</Text>{product.impactClaims.map(claim=><Text key={claim.id} style={[theme.typography.body,{color:theme.colors.text,marginTop:10}]}>{claim.value} {claim.unit} — {claim.label[locale]}</Text>)}</Card>:null}
    <Card style={{marginTop:14}}><Text style={[theme.typography.h2,{color:theme.colors.text}]}>{t('Customer reviews','Потребителски отзиви')}</Text>{reviews.length?reviews.map(review=><View key={review.id} style={{paddingVertical:12,borderBottomWidth:1,borderBottomColor:theme.colors.border}}><Text style={[theme.typography.label,{color:theme.colors.primary}]}>{review.rating}/5 · {review.authorName}{review.verifiedPurchase?` · ${t('Verified purchase','Проверена покупка')}`:''}</Text><Text style={[theme.typography.body,{color:theme.colors.text,marginTop:5}]}>{review.body}</Text></View>):<Text style={[theme.typography.body,{color:theme.colors.textMuted,marginTop:8}]}>{t('No approved reviews yet.','Все още няма одобрени отзиви.')}</Text>}{user&&!reviewSent?<View style={{gap:10,marginTop:16}}><AppInput label={t('Rating (1–5)','Оценка (1–5)')} value={reviewRating} onChangeText={setReviewRating} keyboardType="number-pad"/><AppInput label={t('Your review','Вашият отзив')} value={reviewBody} onChangeText={setReviewBody} multiline numberOfLines={4}/><AppButton label={t('Submit for review','Изпрати за преглед')} variant="secondary" onPress={async()=>{try{await marketplaceService.submitReview(user.id,product.id,Number(reviewRating),reviewBody);setReviewSent(true);}catch(e){setError(e instanceof Error?e.message:String(e));}}}/></View>:null}{reviewSent?<Text style={[theme.typography.body,{color:theme.colors.primary,marginTop:14}]}>{t('Your review is awaiting moderation.','Отзивът ви очаква модерация.')}</Text>:null}</Card>
  </>:null}</Content></ScrollView></Screen>;
}
