/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/auth/confirm-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup-success`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/community`; params?: Router.UnknownInputParams; } | { pathname: `/community/challenges`; params?: Router.UnknownInputParams; } | { pathname: `/community/post/new-post`; params?: Router.UnknownInputParams; } | { pathname: `/habits/goal`; params?: Router.UnknownInputParams; } | { pathname: `/habits/history`; params?: Router.UnknownInputParams; } | { pathname: `/habits/log`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/badges`; params?: Router.UnknownInputParams; } | { pathname: `/community/challenges/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/community/challenges/[id]/log`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/community/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/confirm-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup-success`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/community`; params?: Router.UnknownOutputParams; } | { pathname: `/community/challenges`; params?: Router.UnknownOutputParams; } | { pathname: `/community/post/new-post`; params?: Router.UnknownOutputParams; } | { pathname: `/habits/goal`; params?: Router.UnknownOutputParams; } | { pathname: `/habits/history`; params?: Router.UnknownOutputParams; } | { pathname: `/habits/log`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/badges`; params?: Router.UnknownOutputParams; } | { pathname: `/community/challenges/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/community/challenges/[id]/log`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/community/post/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/callback${`?${string}` | `#${string}` | ''}` | `/auth/confirm-signup${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/signin${`?${string}` | `#${string}` | ''}` | `/auth/signup-success${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `/community/challenges${`?${string}` | `#${string}` | ''}` | `/community/post/new-post${`?${string}` | `#${string}` | ''}` | `/habits/goal${`?${string}` | `#${string}` | ''}` | `/habits/history${`?${string}` | `#${string}` | ''}` | `/habits/log${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/badges${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/callback`; params?: Router.UnknownInputParams; } | { pathname: `/auth/confirm-signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signin`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup-success`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/community`; params?: Router.UnknownInputParams; } | { pathname: `/community/challenges`; params?: Router.UnknownInputParams; } | { pathname: `/community/post/new-post`; params?: Router.UnknownInputParams; } | { pathname: `/habits/goal`; params?: Router.UnknownInputParams; } | { pathname: `/habits/history`; params?: Router.UnknownInputParams; } | { pathname: `/habits/log`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/badges`; params?: Router.UnknownInputParams; } | `/community/challenges/${Router.SingleRoutePart<T>}` | `/community/challenges/${Router.SingleRoutePart<T>}/log` | `/community/post/${Router.SingleRoutePart<T>}` | { pathname: `/community/challenges/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/community/challenges/[id]/log`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/community/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
