import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { AppButton, AppInput, Card, Content, PageHeader, Screen, StatePanel } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { sustainabilityMapService } from '@/features/sustainability-map';
import { uploadSustainabilityPhoto } from '@/features/sustainability-map/media';
import { useAppTheme } from '@/theme';

export default function LocationReviewScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const { user } = useAuth();
  const { id, name } = useLocalSearchParams<{ id: string; name?: string }>();
  const [rating, setRating] = useState(5); const [body, setBody] = useState(''); const [photo, setPhoto] = useState<ImagePicker.ImagePickerAsset | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  if (!user) return <Screen><Content><StatePanel icon="lock-closed-outline" title="Sign in to review" message="Reviews are moderated and linked to one account per place." action={<AppButton label="Sign in" onPress={() => router.replace({ pathname: '/auth/signin', params: { next: '/map' } })} />} /></Content></Screen>;
  const submit = async () => { setBusy(true); setMessage(''); try { await sustainabilityMapService.submitReview(user.id, id, rating, body); if (photo) await uploadSustainabilityPhoto(user.id,id,photo,`Community photo of ${name || 'a sustainability location'}`); setMessage(`Your review${photo?' and photo are':' is'} pending moderation. Approved contributions earn Green Points.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Review failed.'); } finally { setBusy(false); } };
  const choosePhoto = async () => { const permission=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!permission.granted){setMessage('Photo library permission is required to attach a photo.');return;} const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.9}); if(!result.canceled)setPhoto(result.assets[0]); };
  return <Screen><ScrollView keyboardShouldPersistTaps="handled"><Content><PageHeader eyebrow="Community review" title={`Review ${name || 'this place'}`} description="Describe what you observed. Reviews and ratings appear publicly only after moderator approval." action={<AppButton label="Back" icon="arrow-back" variant="ghost" onPress={() => router.back()} />} /><Card style={{ gap: theme.spacing.md }}><View style={{ gap: 8 }}><Text style={[theme.typography.label, { color: theme.colors.text }]}>Rating</Text><View accessibilityRole="radiogroup" style={{ flexDirection: 'row', gap: 8 }}>{[1,2,3,4,5].map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ selected: rating === value }} accessibilityLabel={`${value} stars`} onPress={() => setRating(value)} style={{ minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 24, backgroundColor: rating >= value ? theme.colors.accentSoft : theme.colors.surfaceMuted }}><Ionicons name={rating >= value ? 'star' : 'star-outline'} size={25} color={rating >= value ? theme.colors.primary : theme.colors.textMuted} /></Pressable>)}</View></View><AppInput label="Your review" value={body} onChangeText={setBody} multiline numberOfLines={7} placeholder="Share at least 20 characters about the sustainable service or practice you experienced." style={{ minHeight: 150, textAlignVertical: 'top', paddingTop: 12 }} /><AppButton label={photo?'Change attached photo':'Attach a photo'} icon={photo?'checkmark-circle-outline':'camera-outline'} variant="secondary" onPress={()=>void choosePhoto()}/><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>Photos are re-encoded to remove EXIF location metadata and published only after approval.</Text>{message ? <Text accessibilityLiveRegion="polite" style={[theme.typography.bodySmall, { color: message.startsWith('Your') ? theme.colors.success : theme.colors.danger }]}>{message}</Text> : null}<AppButton label="Submit for moderation" icon="send-outline" loading={busy} onPress={() => void submit()} /></Card></Content></ScrollView></Screen>;
}
