import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { AppButton, AppInput, Card, Content, PageHeader, Screen, StatePanel } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { sustainabilityMapService } from '@/features/sustainability-map';
import { uploadSustainabilityPhoto } from '@/features/sustainability-map/media';
import { useAppTheme } from '@/theme';

export default function LocationReviewScreen() {
  const { theme } = useAppTheme(); const router = useRouter(); const { user } = useAuth();
  const { id, name } = useLocalSearchParams<{ id: string; name?: string }>();
  const [rating, setRating] = useState(5); const [body, setBody] = useState(''); const [photo, setPhoto] = useState<ImagePicker.ImagePickerAsset | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  if (!user) return <Screen><Content><StatePanel icon="lock-closed-outline" title="Влез, за да оставиш отзив" message="Отзивите се проверяват и се свързват с един профил за всяко място." action={<AppButton label="Вход" onPress={() => router.replace({ pathname: '/auth/signin', params: { next: `/map/review/${encodeURIComponent(id)}?name=${encodeURIComponent(name || '')}` } })} />} /></Content></Screen>;
  const submit = async () => { setBusy(true); setMessage(''); try { await sustainabilityMapService.submitReview(user.id, id, rating, body); if (photo) await uploadSustainabilityPhoto(user.id,id,photo,`Снимка от общността на ${name || 'устойчиво място'}`); setMessage(`Отзивът${photo?' и снимката са':' е'} изпратен за проверка. Одобрените приноси носят зелени точки.`); } catch { setMessage('Отзивът не беше изпратен.'); } finally { setBusy(false); } };
  const choosePhoto = async () => { const permission=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!permission.granted){setMessage('Нужно е разрешение за достъп до снимките.');return;} const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.9}); if(!result.canceled)setPhoto(result.assets[0]); };
  return <Screen><ScrollView keyboardShouldPersistTaps="handled"><Content><PageHeader eyebrow="Отзив от общността" title={`Оцени ${name || 'това място'}`} description="Опиши какво си видял. Отзивите и оценките се публикуват само след проверка от модератор." action={<AppButton label="Назад" icon="arrow-back" variant="ghost" onPress={() => router.back()} />} /><Card style={{ gap: theme.spacing.md }}><View style={{ gap: 8 }}><Text style={[theme.typography.label, { color: theme.colors.text }]}>Оценка</Text><View accessibilityRole="radiogroup" style={{ flexDirection: 'row', gap: 8 }}>{[1,2,3,4,5].map((value) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ selected: rating === value }} accessibilityLabel={`${value} звезди`} onPress={() => setRating(value)} style={{ minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 24, backgroundColor: rating >= value ? theme.colors.accentSoft : theme.colors.surfaceMuted }}><Ionicons name={rating >= value ? 'star' : 'star-outline'} size={25} color={rating >= value ? theme.colors.primary : theme.colors.textMuted} /></Pressable>)}</View></View><AppInput label="Твоят отзив" value={body} onChangeText={setBody} multiline numberOfLines={7} placeholder="Сподели поне 20 знака за устойчивата услуга или практика, която си използвал." style={{ minHeight: 150, textAlignVertical: 'top', paddingTop: 12 }} /><AppButton label={photo?'Смени снимката':'Добави снимка'} icon={photo?'checkmark-circle-outline':'camera-outline'} variant="secondary" onPress={()=>void choosePhoto()}/><Text style={[theme.typography.bodySmall,{color:theme.colors.textMuted}]}>Снимките се прекодират, за да се премахнат EXIF данните за местоположение, и се публикуват само след одобрение.</Text>{message ? <Text accessibilityLiveRegion="polite" style={[theme.typography.bodySmall, { color: message.startsWith('Отзивът') ? theme.colors.success : theme.colors.danger }]}>{message}</Text> : null}<AppButton label="Изпрати за проверка" icon="send-outline" loading={busy} onPress={() => void submit()} /></Card></Content></ScrollView></Screen>;
}
